// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMUc-FAtI8ox6LvDN71rv4Y_l-vVJ68GY',
    appId: '1:526077789637:web:9dd68d028a6108cf0d77ac',
    messagingSenderId: '526077789637',
    projectId: 'riesgosapp-5f8b5',
    authDomain: 'riesgosapp-5f8b5.firebaseapp.com',
    storageBucket: 'riesgosapp-5f8b5.firebasestorage.app',
    measurementId: 'G-LX8L4RWZ78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuVgJGbfLl42y_8QtwGJiVgcNX6OWFi6Y',
    appId: '1:526077789637:android:a86999983c1fdbce0d77ac',
    messagingSenderId: '526077789637',
    projectId: 'riesgosapp-5f8b5',
    storageBucket: 'riesgosapp-5f8b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHRjRzb9dqA3K9_PY-cs-1t7YvunGaxJ0',
    appId: '1:526077789637:ios:e566c12ce8d37d320d77ac',
    messagingSenderId: '526077789637',
    projectId: 'riesgosapp-5f8b5',
    storageBucket: 'riesgosapp-5f8b5.firebasestorage.app',
    iosBundleId: 'com.example.gestionRiesgos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHRjRzb9dqA3K9_PY-cs-1t7YvunGaxJ0',
    appId: '1:526077789637:ios:e566c12ce8d37d320d77ac',
    messagingSenderId: '526077789637',
    projectId: 'riesgosapp-5f8b5',
    storageBucket: 'riesgosapp-5f8b5.firebasestorage.app',
    iosBundleId: 'com.example.gestionRiesgos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMUc-FAtI8ox6LvDN71rv4Y_l-vVJ68GY',
    appId: '1:526077789637:web:bbdc1d1ed64701dd0d77ac',
    messagingSenderId: '526077789637',
    projectId: 'riesgosapp-5f8b5',
    authDomain: 'riesgosapp-5f8b5.firebaseapp.com',
    storageBucket: 'riesgosapp-5f8b5.firebasestorage.app',
    measurementId: 'G-VBP9QKRJGY',
  );
}
